import openpyxl
from openpyxl import Workbook

wb = Workbook()

tables = {
    'users': [
        ('id', 'bigint', '○', '主キー'),
        ('email', 'string(255)', '○', 'ユニーク'),
        ('password', 'string(255)', '○', ''),
        ('user_type', "enum('teacher','individual_employer','corporate_employer')", '○', ''),
        ('status', "enum('active','inactive','pending')", '', 'デフォルトpending'),
        ('email_verified_at', 'timestamp', '', ''),
        ('last_login', 'timestamp', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
        ('avatar', 'string(255)', '', 'デフォルトusers/default.png'),
        ('messenger_color', 'string(20)', '', 'デフォルト#2180f3'),
        ('dark_mode', 'boolean', '', 'デフォルトfalse'),
        ('active_status', "enum('online','offline')", '', ''),
    ],
    'teachers': [
        ('id', 'bigint', '○', '主キー'),
        ('user_id', 'bigint', '○', 'users外部キー'),
        ('first_name', 'string(50)', '○', ''),
        ('last_name', 'string(50)', '○', ''),
        ('profile_image', 'text', '', ''),
        ('phone', 'string(20)', '', ''),
        ('address', 'text', '', ''),
        ('nearest_station', 'string(100)', '', ''),
        ('university', 'string(100)', '', ''),
        ('faculty', 'string(100)', '', ''),
        ('graduation_year', 'integer', '', ''),
        ('teaching_experience', 'integer', '', 'デフォルト0'),
        ('subject', 'string(50)', '○', ''),
        ('grade_level', 'string(50)', '○', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'employers': [
        ('id', 'bigint', '○', '主キー'),
        ('user_id', 'bigint', '○', 'users外部キー'),
        ('name', 'string(100)', '○', ''),
        ('contact_person', 'string(100)', '', ''),
        ('phone', 'string(20)', '', ''),
        ('address', 'text', '', ''),
        ('nearest_station', 'string(100)', '', ''),
        ('recruiting_subject', 'string(100)', '', ''),
        ('description', 'text', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'scout_requests': [
        ('id', 'bigint', '○', '主キー'),
        ('employer_id', 'bigint', '○', 'employers外部キー'),
        ('teacher_id', 'bigint', '○', 'teachers外部キー'),
        ('message', 'string(1000)', '', ''),
        ('status', "enum('pending','accepted','rejected')", '○', ''),
        ('expires_at', 'timestamp', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'corporate_jobs': [
        ('id', 'bigint', '○', '主キー'),
        ('employer_id', 'bigint', '○', 'users外部キー'),
        ('title', 'string(100)', '○', ''),
        ('description', 'text', '', ''),
        ('subjects', 'text', '', ''),
        ('target_grades', 'text', '', ''),
        ('location', 'text', '', ''),
        ('employment_type', "enum('full_time','part_time','contract')", '○', ''),
        ('salary_type', "enum('hourly','monthly','yearly')", '○', ''),
        ('salary_min', 'decimal(10,2)', '', ''),
        ('salary_max', 'decimal(10,2)', '', ''),
        ('benefits', 'text', '', ''),
        ('requirements', 'text', '', ''),
        ('application_deadline', 'date', '', ''),
        ('start_date', 'date', '', ''),
        ('status', "enum('draft','active','closed')", '', 'デフォルトdraft'),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'individual_jobs': [
        ('id', 'bigint', '○', '主キー'),
        ('employer_id', 'bigint', '○', 'employers外部キー'),
        ('title', 'string(100)', '○', ''),
        ('description', 'text', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'surveys': [
        ('id', 'bigint', '○', '主キー'),
        ('employer_id', 'bigint', '○', 'employers外部キー'),
        ('title', 'string(100)', '○', ''),
        ('description', 'text', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'survey_responses': [
        ('id', 'bigint', '○', '主キー'),
        ('survey_id', 'bigint', '○', 'surveys外部キー'),
        ('user_id', 'bigint', '○', 'users外部キー'),
        ('answer', 'text', '', ''),
        ('submitted_at', 'timestamp', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'bookmarks': [
        ('id', 'bigint', '○', '主キー'),
        ('user_id', 'bigint', '○', 'users外部キー'),
        ('bookmarkable_type', 'string(50)', '○', ''),
        ('bookmarkable_id', 'integer', '○', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'individual_contracts': [
        ('id', 'bigint', '○', '主キー'),
        ('teacher_id', 'bigint', '○', 'teachers外部キー'),
        ('employer_id', 'bigint', '○', 'employers外部キー'),
        ('job_id', 'bigint', '○', 'individual_jobs外部キー'),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'sessions': [
        ('id', 'string', '○', '主キー'),
        ('user_id', 'bigint', '', 'users外部キー'),
        ('ip_address', 'string(45)', '', ''),
        ('user_agent', 'text', '', ''),
        ('payload', 'longtext', '○', ''),
        ('last_activity', 'integer', '○', ''),
    ],
    'password_reset_tokens': [
        ('email', 'string', '○', '主キー'),
        ('token', 'string', '○', ''),
        ('created_at', 'timestamp', '', ''),
    ],
    'failed_jobs': [
        ('id', 'bigint', '○', '主キー'),
        ('uuid', 'string', '○', 'ユニーク'),
        ('connection', 'text', '○', ''),
        ('queue', 'text', '○', ''),
        ('payload', 'longtext', '○', ''),
        ('exception', 'longtext', '○', ''),
        ('failed_at', 'timestamp', '○', ''),
    ],
    'personal_access_tokens': [
        ('id', 'bigint', '○', '主キー'),
        ('tokenable_type', 'string', '○', ''),
        ('tokenable_id', 'bigint', '○', ''),
        ('name', 'string', '○', ''),
        ('token', 'string(64)', '○', 'ユニーク'),
        ('abilities', 'text', '', ''),
        ('last_used_at', 'timestamp', '', ''),
        ('expires_at', 'timestamp', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'chatify_favorites': [
        ('id', 'bigint', '○', '主キー'),
        ('user_id', 'bigint', '○', 'users外部キー'),
        ('favorite_id', 'bigint', '○', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
    'chatify_messages': [
        ('id', 'bigint', '○', '主キー'),
        ('type', 'string', '○', ''),
        ('from_id', 'bigint', '○', ''),
        ('to_id', 'bigint', '○', ''),
        ('body', 'text', '', ''),
        ('attachment', 'text', '', ''),
        ('created_at', 'timestamp', '○', ''),
        ('updated_at', 'timestamp', '○', ''),
    ],
}

for table_name, columns in tables.items():
    ws = wb.create_sheet(title=table_name)
    ws.append(['カラム名', '型', '必須', '備考'])
    for col in columns:
        ws.append(col)

del wb['Sheet']
wb.save('テーブル定義_全体_20250420.xlsx')
